### ISSUE TITLE
Ticket Type not set or selectable

### ISSUE THREAD

**Issue by AugmentBLU** [responsiv/support-plugin#2]
Hello,

**bug summary**
Ticket type is not being set after ticket has been submitted and cannot be set manually in the back-end.

**reproduce steps**
1. In the back-end, create a CMS page and include the supportTicketSubmit component
2. Set options of supportTicketSubmit component, ticket type is set to `Technical Support`
3. Save page
4. In another browser/tab, sign in as a front-end user and go to the new supportTicketSubmit page
5. Enter ticket details and submit
6. Go back to admin/backend area and navigate to Support > Tickets
7. Click newly received ticket
8. Ticket Type is blank and cannot be set manually

**expected behavior**
The Ticket Type in the newly received ticket should be set according to the option selected in the component options

**actual behavior**
Ticket Type is blank and cannot be set manually

**Comment by daftspunk** [comment]
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by daftspunk** [comment]
Please use a separate issue for each concern. Thanks

**Comment by AugmentBLU** [comment]
@daftspunk I've updated the issue - sorry I didn't follow the guidelines, hopefully this is better.

**Comment by daftspunk** [comment]
Sorry for the delay in responding. I checked with the latest code and could not replicate this. Let me know if it is still an issue

**Comment by artistro08** [comment]
Hey @daftspunk, I have this issue as well. I created a ticket and I couldn't change the ticket type as well. I'm on October v2.1.4

**Comment by artistro08** [comment]
Nevermind! Figured it out. Works if you let the user set a status.
